NEX-1459 integrate yum s3 plugin into BV infrastructure
bazaarvoice/yum-s3-iam pull request #1
Opened 2018-11-09 12:35 UTC by mike-unitskyi

2018-11-09 12:37 UTC, Emperorex commented
Changes looks good to me. Package yum-plugin-s3-iam-1.2.2-1.noarch has been tested on Amazon Linux 2 - no issues were found

2018-11-13 21:09 UTC, ohhatiya requested changes
I feel like it would be better to put our specific test and release pieces in a separate repo, and that way we don't need to have a forked version of the plugin. I *think* most of these changes aren't necessary to actually do the build, and if they are they might be accepted as pull requests to origin.

Docker compose lets you specify a git repository as a context for building an image, so we could probably even just specify upstream's Dockerfile.test as one image in our compose and then set up another one for our end to end tests and release (although I haven't figured out the best way to get the RPM from one to the next - could maybe specify a volume where it gets built, or set up a separate multi-stage Dockerfile that pulls it out for the tests).

For the tests themselves, it's really just testing the dependency resolution behavior of yum and that we have things correctly specified. It might be nice to have something that tests actually pulling stuff from an S3 repo. The old plugin also allows URLs like ${bucket}.s3-website.amazonaws.com. Would be nice to verify that works (or if it doesn't we'll at least know to tell people to change their repo definitions).

2018-11-13 21:09 UTC, ohhatiya commented on Makefile
> +RPM_TOPDIR ?= $(CURDIR)/build
topdir is set as:
```
_topdir    %{getenv:HOME}/rpmbuild
```
So I think $HOME isn't set for some reason (either make or docker is likely running in a way there's no $HOME). If we can find a way to run with a $HOME, it should work as is.

2018-11-13 21:09 UTC, ohhatiya commented on Makefile
> +	rpmbuild --target=linux $(RPMBUILD_ARGS) -ba --clean $(NAME).spec
Hmm, is this not the default for you? I have:
```console
# rpm --showrc | grep target_os
-11= _target_os	linux
```

2018-11-13 21:09 UTC, ohhatiya commented on Dockerfile
> +        git                                                                     \
A lot of this stuff isn't actually used.

2018-11-13 21:09 UTC, ohhatiya commented on s3iam.repo
> +baseurl=https://nexus-public-artifacts.s3.amazonaws.com/yum-repo
This file is meant to be an example repo definition. I'd set up a separate one for testing dependency configuration.

2018-11-13 21:09 UTC, ohhatiya commented on yum-plugin-s3-iam.spec
> +Provides:  yum-s3, yum-plugin-s3
Rather than do this, would it make sense to make a meta-package that provides these and requires yum-plugin-s3-iam? That way our version numbers don't get too out of sync from upstream.

2018-11-14 07:15 UTC, mike-unitskyi commented on Makefile
> +	rpmbuild --target=linux $(RPMBUILD_ARGS) -ba --clean $(NAME).spec
without specifying targetOS for macos I cannot install package on rpm based OS

2018-11-14 07:15 UTC, mike-unitskyi commented on Dockerfile
> +        git                                                                     \
agree, will remove

2018-11-15 23:42 UTC, ohhatiya commented on Makefile
> +	rpmbuild --target=linux $(RPMBUILD_ARGS) -ba --clean $(NAME).spec
Interesting. It works fine for me. Wonder if Docker is running things differently for us.

2022-07-28 06:28 UTC, closed without merging